workflows:
  ios-workflow:
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jacobrubin.workoutapp
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: flutter analyze
        ignore_failure: true
      - name: Flutter test
        script: flutter test
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
          --build-name=1.1.$PROJECT_BUILD_NUMBER \
          --build-number=$PROJECT_BUILD_NUMBER \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - jacrub18@gmail.com
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - "Jacob Rubin Fan Club"
