// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11IgpyHLue-eMmHQGrAKjrx5trQWJqaA',
    appId: '1:951489627776:android:b6c8867d2d93ccd9d00865',
    messagingSenderId: '951489627776',
    projectId: 'workout-app-6fe11',
    storageBucket: 'workout-app-6fe11.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5rT7_slPp5QNkzSiKgJX0dkwcB4rGotI',
    appId: '1:951489627776:web:6d1f81e28759cf83d00865',
    messagingSenderId: '951489627776',
    projectId: 'workout-app-6fe11',
    authDomain: 'workout-app-6fe11.firebaseapp.com',
    storageBucket: 'workout-app-6fe11.appspot.com',
    measurementId: 'G-RJ58HTH2G1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfC-YFJl7W6YaEJTwpbLRyH8eIGxgIlWg',
    appId: '1:951489627776:ios:f8272a3d8efe8c75d00865',
    messagingSenderId: '951489627776',
    projectId: 'workout-app-6fe11',
    storageBucket: 'workout-app-6fe11.appspot.com',
    iosBundleId: 'com.jacobrubin.workoutapp',
  );

}