final List<String> targetMuscles = [
  'Abductors',
  'Abs',
  'Adductors',
  'Biceps',
  'Calves',
  'Cardiovascular System',
  'Delts',
  'Forearms',
  'Glutes',
  'Hamstrings',
  'Lats',
  'Levator Scapulae',
  'Pectorals',
  'Quads',
  'Serratus Anterior',
  'Spine',
  'Traps',
  'Triceps',
  'Upper Back'
];

final List<String> equipment = [
  'Assisted',
  'Band',
  'Barbell',
  'Body Weight',
  'Bosu Ball',
  'Cable',
  'Dumbbell',
  'Elliptical Machine',
  'Ez Barbell',
  'Hammer',
  'Kettlebell',
  'Leverage Machine',
  'Medicine Ball',
  'Olympic Barbell',
  'Resistance Band',
  'Roller',
  'Rope',
  'Skierg Machine',
  'Sled Machine',
  'Smith Machine',
  'Stability Ball',
  'Stationary Bike',
  'Stepmill Machine',
  'Tire',
  'Trap Bar',
  'Upper Body Ergometer',
  'Weighted',
  'Wheel Roller'
];
